In [3]:
import numpy as np

In [8]:
k1 = np.array([1, 11])
print(k1)
k2 = np.zeros((2, 5))
print(k2)
k3 = np.ones(2)
print(k3)
k4 = np.arange(1, 5)
print(k4)

[ 1 11]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1.]
[1 2 3 4]


In [10]:
k5 = np.arange(1, 6)
print(f"shape: {k5.shape}        dtype: {k5.dtype}")

shape: (5,)        dtype: int64


In [20]:
k6 = np.arange(0, 6).reshape(3, 2) # перевернул масив сделав его 3 на 2
print(k6[1][1])  # 1 по строке и 1 по столбцу элемент
print(k6[0:2]) # 0 и 1 элемент к6


3
[[0 1]
 [2 3]]


In [32]:
k7 = np.arange(1, 4, dtype=float)
k8 = np.arange(5, 8, dtype=float)
print("k7:", k7)
print("k8:", k8)
print(k7 + k8)
print(k7 * 3)
print(k7 / 3)
print("mean:", k7.mean())
print("сумма:", np.sum(k7))

k7: [1. 2. 3.]
k8: [5. 6. 7.]
[ 6.  8. 10.]
[3. 6. 9.]
[0.33333333 0.66666667 1.        ]
mean: 2.0
сумма: 6.0
